name: Build LaTeX

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Build Docker image
        run: docker build -t latex-builder .

      - name: Build pdf
        run: docker run --rm -v "${{ github.workspace }}:/workspace" latex-builder make
